### PR TITLE
Fix Rails 5 alias_method_chain deprecation

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by wagenet** [comment]
Test failures are unrelated to my change.

**Comment by atd** [comment]
Thank you for the pull request @wagenet 

Sorry but I have been disconnected from Rails for 3 years and I am not aware on how engine's path are managed in Rails 5

Tests should also be fixed. I have done some work on the travis branch, but an update of the dummy app is needed.

I hope I get some time for it in a couple of weeks. Sorry for that. Of course, a pull request that updates the tests is very welcomed

**Comment by gwalshington** [comment]
I'm currently running into this issue as well. Any update on this issue?

**Comment by wagenet** [comment]
@gwalshington my branch should work for now.

**Comment by wagenet** [comment]
@atd to be clear, this doesn't change how paths are managed, it just changes how the method overwrite happens to not use `alias_method_chain`.

**Comment by wagenet** [comment]
I've closed this pull request, but for the time being I will continue to leave the branch if anyone is using it. However, I would recommend not relying upon it in case it gets deleted in the future.

**Pull request closed without merging**
